---
title: "Examles of attribute propagation with data.tree"
output:
  html_document:
    toc:
      true
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE}
library(taxPPro)
library(bugphyzz)
library(data.tree)
library(dplyr)
```

# Get NCBI data

```{r get and modify ncbi data, message=FALSE}
ncbi_taxids <- get_ncbi_taxids(keyword = 'b', with_taxids = TRUE)
new_ncbi_taxids <- taxname2taxid(tax_tbl = ncbi_taxids)
cond1 <- new_ncbi_taxids$Rank == 'species'
cond2 <- new_ncbi_taxids$superkingdom == '2'
bacteria <- new_ncbi_taxids[cond1 & cond2,]
no_select_cols <- c(
    'species', 'strain', 'Taxon_name', 'Parent_NCBI_ID', 'Rank'
)
bacteria <- bacteria[,!colnames(bacteria) %in% no_select_cols]
for (i in seq_along(bacteria)) {
  bacteria[[i]] <- fillNAs(bacteria[[i]])
}
head(bacteria)
```

# Convert NCBI data to data.tree

Add path string

```{r add pathString}
pathString <- paste(
    'k__', bacteria$superkingdom, # root
    '|||p__', bacteria$phylum,
    '|||c__', bacteria$class,
    '|||o__', bacteria$order,
    '|||f__', bacteria$family,
    '|||g__', bacteria$genus,
    '|||s__', bacteria$NCBI_ID,
    sep = ''
)

bacteria$pathString <- pathString
bacteria$NCBI_ID <- paste0('s__', bacteria$NCBI_ID) 
head(bacteria$pathString)
```
Convert to data.tree

```{r concert to data.tree}
start_time <- Sys.time()
bac_tree <- as.Node(bacteria, pathDelimiter = '|||')
end_time <- Sys.time()
(elapsed_time <- difftime(end_time, start_time))
```

A small portion of the tree

```{r print tree}
print(bac_tree, limit = 20)
```

# Bugphyzz

```{r divide into attributes}
aer <- physiologies('aerophilicity', remove_false = TRUE)[[1]]
aer <- preSteps(aer, tax.id.type = 'NCBI_ID', remove_false = TRUE)
dic <- c('g__', 's__', 't__')
names(dic) <- c('genus', 'species', 'strain')
aer$NCBI_ID <- paste0(dic[aer$Rank], aer$NCBI_ID)
select_cols <- c(
  'NCBI_ID', 'Attribute', 'Attribute_value', 'Evidence',  'Frequency', 
  'Confidence_in_curation', 'Attribute_source', 'Score'
)
aer <- unique(aer[, select_cols])
aer <- aer[which(grepl('^[gs]__', aer$NCBI_ID)),]
sp <- split(aer, aer$NCBI_ID)
```

# aer + data.tree

Adding information

```{r}
bac_tree$Do(function(node) node$Attribute_info <- sp[[node$name]])
```

Let's check it

```{r}
print(e_tree, 'aerobic', 'facultatively anaerobic') |> View()

```

Let's print it

```{r}
print(bac_tree, 'Attribute_info', limit = 10)
```


# E coli

Add separate attributes

```{r}
e <- bacteria[bacteria$genus == '561',]
e_tree <- as.Node(e, pathDelimiter = '|||')
a <- split(aer, factor(aer$Attribute))

for (i in seq_along(a)) {
  attr_name <- names(a)[i]
  lst_vct <- split(a[[i]], factor(a[[i]][['NCBI_ID']]))
  e_tree$Do(function(node) node[[attr_name]] <- lst_vct[[node$name]]$Score)
}

e_tree$Do(function(node) node$aerobic <- Aggregate(node, 'aerobic', function(x) sum(x[!is.na(x)])), traversal = 'post-order')
e_tree$Do(function(node) node$`facultatively anaerobic` <- Aggregate(node, 'facultatively anaerobic', function(x) sum(x[!is.na(x)])), traversal = 'post-order')

e_tree$Do(function(node) if (is.na(node$aerobic)) { node$aerobic <- node$parent$aerobic})
e_tree$Do(function(node) if (is.na(node$`facultatively anaerobic`)) { node$`facultatively anaerobic` <- node$parent$`facultatively anaerobic`})

```



```{r}
tbl <- ToDataFrameTree(e_tree, 'aerobic', 'facultatively anaerobic')
m <- tbl |> 
  tibble::column_to_rownames('levelName') |> 
  as.matrix()

rownames(m) <- sub('^.*([kpcofgst]__[0-9]+).*$', '\\1', rownames(m))
m2 <- t(apply(t(m), 2, function(x) x / sum(x)))
```


```{r}
e_tree$p__1224$c__1236$o__91347$f__543$g__561$aerobic 
```

```{r}





Aggregate(
  node = e_tree,
  attribute = 'aerobic',
  aggFun = function(x) sum(x[!is.na(x)])
)
```

# 

```{r}
e <- bacteria[bacteria$genus == '561',]
e_tree <- as.Node(e, pathDelimiter = '|||')
a <- split(aer, factor(aer$Attribute))
e_tree$Do(function(node) node$Attribute_info <- sp[[node$name]])
```


```{r}
Aggregate(
  node = e_tree$p__1224$c__1236$o__91347$f__543$g__561,
  attribute = 'Attribute_info',
  aggFun = function(x) cbind(x)
)

```


# Session infomation
```{r}
sessioninfo::session_info()
```
