---
title: "signatures in bugsigdbr"
output: html_document
date: "2022-08-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(bugsigdbr)
library(dplyr)
```

# Import BugSigDB database

```{r import data}
data <- importBugSigDB()
```

# Create signatrues with exact and non-exact taxonomic level

```{r create signatrues}
sigs_1 <- getSignatures(
    data, tax.id.type = 'taxname', tax.level = 'phylum', exact.tax.level = TRUE
)

sigs_2 <- getSignatures(
    data, tax.id.type = 'taxname', tax.level = 'phylum', exact.tax.level = FALSE
)

```

# Find common signatures in both sets

```{r common sigs}
common_names <- intersect(names(sigs_1), names(sigs_2))
sig1 <- sigs_1[common_names]
sig2 <- sigs_2[common_names]
```

# Take one as an example

```{r one example signature}
exact_sig <- sig1[length(sig1)]
non_exact_sig <- sig2[length(sig2)]
exact_sig
```

```{r}
non_exact_sig
```

# How it looks like in the dataframe

```{r }
x <- filter(data, Study == 'Study 609', `Abundance in Group 1` == 'decreased')
meta <- x$`MetaPhlAn taxon names`
DT::datatable(arrange(data.frame(taxa = meta[[1]])))
```

# Session info

```{r}
sessionInfo()
```



