---
title: "NCBI taxonomy and completeness"
output:
    html_document:
        toc: true
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE}
library(taxPPro)
library(bugphyzz)
library(dplyr)
library(purrr)
library(ggplot2)
```

```{r}
ncbi_taxonomy <- get_ncbi_taxonomy()
ncbi_taxonomy
```

```{r}
ranks <- c(
    'strain', 'species', 'genus', 'family', 'order', 'class', 'phyum', 'kingdom'
)

ncbi_counts <- ncbi_taxonomy |> 
    dplyr::filter(Rank %in% ranks) |> 
    count(Rank)

rank_levels <- sort(ranks[ranks %in% ncbi_counts$Rank])
    
ncbi_counts |> 
    mutate(Rank = factor(Rank, levels = rank_levels)) |> 
    ggplot(aes(Rank, n)) +
    geom_col() +
    geom_label(aes(label = n))
    
```

# Get all NCBI IDs in bugphyzz

```{r, message=FALSE}
## Only datasets imported with the physiologies function
phys <- map(physiologies(), as_tibble)
bugphyzz_taxids <- phys |> 
    map(~.x$NCBI_ID) |> 
    unlist(recursive = TRUE) |> 
    as.character() |> 
    unique()

```

# Get NCBI taxids grouped as in the NCBI taxonomy statistics page

```{r}
ncbi_ids <- import_ncbi_ids()
```


# Compare how many of the bugphyzz IDs are in each group

```{r}
output <- vector('list', length(ncbi_ids))
names(output) <- names(ncbi_ids)
for (i in seq_along(output)) {
    output[[i]] <- unique(intersect(bugphyzz_taxids, ncbi_ids[[i]]))
}
map_dbl(output, ~ length(.x) / length(bugphyzz_taxids) * 100) |> 
    {\(y) sort(y, decreasing = TRUE)}()
```

```{r}
sum(ncbi_ids$exclude_uncultured %in% ncbi_ids$all_ids)
```


It seems that excluding uncultured taxids would give the highest completeness
values while still keeping the lowest number of taxa

```{r}
uncultured_taxids <- ncbi_ids$exclude_uncultured
ncbi_taxonomy_remove_uncultured <- ncbi_taxonomy |> 
    filter(NCBI_ID %in% uncultured_taxids)

```

```{r}

ncbi_counts_remove_uncultured <- ncbi_taxonomy_remove_uncultured |> 
    dplyr::filter(Rank %in% ranks) |> 
    count(Rank)

rank_levels_2 <- sort(ranks[ranks %in% ncbi_counts_remove_uncultured$Rank])
    
ncbi_counts_remove_uncultured |> 
    mutate(Rank = factor(Rank, levels = rank_levels_2)) |> 
    ggplot(aes(Rank, n)) +
    geom_col() +
    geom_label(aes(label = n))
```



