---
title: "Effect of uncertainty in tip annotations"
subtitle: 'Multistate-intersection'
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ape)
library(phytools)
library(dplyr)
library(tidyr)
```

## Prepare data and tree

```{r}
data('primate.tree')
data('primate.data')
tree <- primate.tree
data <- primate.data
data <- data[tree$tip.label,]
rownames(data) <- paste0('taxon', 1:nrow(data))
tree$tip.label <- paste0('taxon', 1:Ntip(tree))
original <- data |>
    tibble::rownames_to_column(var = 'Taxa') |>
    select(Taxa, Activity_pattern) |>
    mutate(Presence = 1) |>
    pivot_wider(
        names_from = 'Activity_pattern', values_from = 'Presence',

                values_fill = 0
    ) |>
    arrange(Taxa) |>
    tibble::column_to_rownames(var = 'Taxa') |>
    as.matrix()
colnames(original) <- c(LETTERS[1:3])

myFun <- function(mat, per_uncertain = 0.1) {
    n_row <- nrow(mat)
    n <- round(n_row * per_uncertain)
    rows <- sample(x = 1:nrow(mat), size = n, replace = FALSE)
    mat[rows,] <- rep(1/ncol(mat), ncol(mat))
    mat
}
```

# No uncertainty

```{r}
fit <- fitMk(tree = tree, x = original,
              model = "ARD", pi = "fitzjohn",
              lik.func = "pruning", logscale = TRUE)
ace <- ancr(fit, tips=TRUE)
plot(ace, args.plotTree = list(direction="upwards"))
title(main = '0% uncertain tips', line = -1)
```

# Uncertaintity

## 99% uncertainty

```{r}
set.seed(123)
m99 <- myFun(original, 0.99)
m99 <- m99[tree$tip.label,]
fit99 <- fitMk(tree = tree, x = m99,
              model = "ARD", pi = "fitzjohn",
              lik.func = "pruning", logscale = TRUE)
ace99 <- ancr(fit99, tips=TRUE)
plot(ace99, args.plotTree = list(direction="upwards"))
title(main = '99% uncertain tips', line = -1)
```

## 95% uncertainty

```{r}
set.seed(123)
m95 <- myFun(original, 0.95)
m95 <- m95[tree$tip.label,]
fit95 <- fitMk(tree = tree, x = m95,
              model = "ARD", pi = "fitzjohn",
              lik.func = "pruning", logscale = TRUE)
ace95 <- ancr(fit95, tips=TRUE)
plot(ace95, args.plotTree = list(direction="upwards"))
title(main = '95% uncertain tips', line = -1)

```

## 70% uncertainty

```{r}
set.seed(123)
m75 <- myFun(original, 0.7)
m75 <- m75[tree$tip.label,]
fit75 <- fitMk(tree = tree, x = m75,
              model = "ARD", pi = "fitzjohn",
              lik.func = "pruning", logscale = TRUE)
ace75 <- ancr(fit75, tips=TRUE)
plot(ace75, args.plotTree = list(direction="upwards"))
title(main = '70% uncertain tips', line = -1)
```

# Session information

```{r}
sessioninfo::session_info()
```


