---
title: "Completeness"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  warning = FALSE
)
```

```{r setup, message=FALSE}
library(taxPPro)
library(dplyr)
library(ggplot2)
library(bugphyzz)
library(purrr)
```

```{r}
ncbi_taxonomy <- get_ncbi_taxonomy() |> 
    mutate(strain = ifelse(rank == 'strain', tax_name, NA))

dim(ncbi_taxonomy)
```

```{r}
head(ncbi_taxonomy)
```

```{r}
ranks <- c(
    'strain', 'species', 'genus', 'family', 'order', 'class', 'phyum', 'kingdom'
)

ncbi_counts <- ncbi_taxonomy |> 
    dplyr::filter(rank %in% ranks) |> 
    vapply(function(x) length(unique(x)), integer(1))

ncbi_counts_tbl <- tibble::tibble(
    rank = names(ncbi_counts), n = ncbi_counts
)

ncbi_counts_tbl |> 
    filter(rank %in% ranks) |> 
    mutate(rank = factor(rank, levels = ranks)) |> 
    ggplot(aes(reorder(rank, n), n)) +
    geom_col() +
    geom_label(aes(label = n)) +
    labs(
        title = 'NCBI totals',
        x = 'rank'
    )
    
```

Completeness

```{r, message=FALSE}
phys = physiologies() |> 
    lapply(as_tibble)
```


```{r}
phys_no_dup <- map(phys, ~ {
    .x |> filter_dataset_for_propagation() |> 
        # remove_taxa_duplicates() |> 
        ci_to_scores() |> 
        distinct()
}) |> 
    keep(~!nrow(.x) == 0)

phys_filtered_counts <- map(phys_no_dup, ~ {
    counts <- table(.x$Rank)
    tibble::tibble(rank =  names(counts), n = as.integer(counts))
}) |> 
    bind_rows(.id = 'dataset')

phys_filtered_counts |> 
    ggplot(aes(reorder(dataset, n), n)) +
    geom_col(aes(fill = rank)) +
    labs(
        title = 'Totals across bugphyzz datasets',
        x = 'dataset'
    ) +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1)
    )
```
```{r}
phys_counts <- map(phys, ~ {
    .x <- dplyr::filter(.x, Rank %in% ranks)
    counts <- table(.x$Rank)
    tibble::tibble(rank =  names(counts), n = as.integer(counts))
}) |> 
    bind_rows(.id = 'dataset')

phys_counts |> 
    ggplot(aes(reorder(dataset, n), n)) +
    geom_col(aes(fill = rank)) +
    labs(
        title = 'Totals across bugphyzz datasets',
        x = 'dataset'
    ) +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1)
    )
```





