---
title: "phytools"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE}
library(bugphyzz)
library(taxPPro)
library(data.tree)
library(phytools)
library(dplyr)
library(purrr)
library(tidyr)
```

Load bugphyzz data (one physiology: aerophilicity):

```{r import physiology data}
select_cols <- c(
    'NCBI_ID', 'Taxon_name', 'Attribute', 'Attribute_value', 'Attribute_source',
    'Frequency', 'Parent_NCBI_ID'
)

aer <- physiologies('aerophilicity')[[1]]
phys_data <- aer |> 
    as_tibble() |> 
    select(all_of(select_cols)) |> 
    filter(Attribute_value == TRUE) |> # only use TRUE values for this one
    filter(
        !((is.na(NCBI_ID) | NCBI_ID == 'unknown') & is.na(Parent_NCBI_ID))
    ) |> 
    distinct()
dim(phys_data)
```

Some of these annotations cannot be mapped to a phylogenetic/taxonomic tree
because they don't have an NCBI taxonomy ID (taxid). They have Parent NCBI_IDs,
however. Let's use them for that. I call this 'early ASR', we cannot really
use these annotations.

```{r}
lgl_vct <- is.na(phys_data$NCBI_ID) | phys_data$NCBI_ID == 'unknown'
set_with_ids <- phys_data |> 
    filter(!lgl_vct) |> 
    group_by(NCBI_ID) |> 
    mutate(Taxon_name = paste0(sort(unique(Taxon_name)), collapse = '|')) |> 
    ungroup() |> 
    distinct()
dim(set_with_ids)
```

```{r}
set_without_ids <- filter(phys_data, lgl_vct) # this will be used for ASR
dim(set_without_ids)
```

```{r}
set_without_ids |> 
    
```

















Load data:

```{r}
data("primate.tree")
data("primate.data")
tree <- primate.tree
data <- primate.data
rm(primate.tree)
rm(primate.data)
activity <- data$Activity_pattern
names(activity) <- rownames(data)
m <- to.matrix(activity, levels(activity))
m[,] <- rep(1/ncol(m), ncol(m))
labs <- rownames(m)[which(grepl('Galago', rownames(m)))]
for (i in seq_along(labs)) {
    m[labs[i],] <- c(0, 0, 1)
}
fit <- fitMk(
    tree = tree, x = m, model = 'ARD', pi = "fitzjohn", logscale = TRUE, 
    lik.func = "pruning"
)
ace <- ancr(fit, tips = TRUE)
res <- ace$ace

```






```{r}
plot(ace, args.plotTree = list(direction = "upwards"))
tips <- sapply(labs, function(x, y) which(y == x), y = tree$tip.label)
add.arrow(tree, tips, arrl = 3, offset = 2, lwd = 2, col = palette()[4])
```

