---
title: "bugphyzz stats"
output:
    html_document:
        toc: true
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE}
library(taxPPro)
library(bugphyzz)
library(dplyr)
library(purrr)
library(tidyr)
library(ggplot2)
```

# Import data

```{r, message=FALSE}
phys <- map(physiologies(), as_tibble)
phys[['fatty acid composition']] <- fattyAcidComposition()
```

# Total counts

```{r}
total_counts <- phys |> 
    map(counts_total) |> 
    bind_rows(.id = 'spreadsheet') |> 
    arrange(n) 

total_counts_order <- total_counts |> 
    pull(spreadsheet)

rank_counts <- phys |> 
    map(counts_per_rank) |> 
    bind_rows(.id = 'spreadsheet') |> 
    mutate(
        spreadsheet = factor(spreadsheet, levels = total_counts_order),
        Rank = factor(Rank, levels = c('genus', 'species', 'strain'))
    )

DT::datatable(
    data = total_counts, filter = 'top'
)
```

```{r}
rank_counts |> 
    ggplot(aes(spreadsheet, n)) +
    geom_col(aes(fill = Rank)) +
    labs(
        title = 'Total counts of annotations per spreadsheet',
        subtitle = 'Totals were calculated previous to ASR/Inheritance',
        x = 'Spreadsheet', y = '# annotations'
    ) +
    scale_fill_brewer(type = 'qual', palette = 'Set1') +
    theme_bw() +
    theme(
        panel.grid.major.y = element_blank()
    ) +
    coord_flip()
```

> Antimicrobial resistance are marked as species, but it's actually strains.

# Propagate with majority vote

```{r, message=FALSE}
phys_propagate <- phys |> 
    map(propagate)
```

## Counts after majority vote 

```{r}
phys_propagate_total_counts <- phys_propagate |> 
    map(counts_total) |> 
    bind_rows(.id = 'spreadsheet') |> 
    arrange(n)

phys_prop_order <- phys_propagate_total_counts$spreadsheet

phys_prop_ranks <-  phys_propagate |> 
    map(counts_per_rank) |> 
    bind_rows(.id = 'spreadsheet') |> 
    mutate(
        spreadsheet = factor(spreadsheet, levels = total_counts_order),
        Rank = factor(Rank, levels = c('genus', 'species', 'strain'))
    )

DT::datatable(
    data = phys_propagate_total_counts, filter = 'top'
)
```



```{r}
phys_prop_ranks |> 
    ggplot(aes(spreadsheet, n)) +
    geom_col(aes(fill = Rank)) +
    labs(
        title = 'Total counts of annotations per spreadsheet',
        subtitle = 'Totals were calculated previous to ASR/Inheritance',
        x = 'Spreadsheet', y = '# annotations'
    ) +
    scale_fill_brewer(type = 'qual', palette = 'Set1') +
    theme_bw() +
    theme(
        panel.grid.major.y = element_blank()
    ) +
    coord_flip()
```

# Comparing counts

Total numbers before ASR:

```{r}
sum(map_int(phys, nrow))
```

Total numbers after ASR (majority vote):

```{r}
sum(map_int(phys_propagate, nrow))
```

Comparing counts per spreadsheet:

```{r}
total_counts <- total_counts |> 
    mutate(method = 'before_asr') |> 
    relocate(method)

phys_propagate_total_counts <- phys_propagate_total_counts |> 
    mutate(method = 'majority_vote') |> 
    relocate(method)

all <- bind_rows(total_counts, phys_propagate_total_counts) |> 
    mutate(spreadsheet = factor(spreadsheet, levels = total_counts_order))

DT::datatable(
    data = all, filter = 'top'
)
```


A plot:

```{r, fig.height=9, fig.width=10}
all |> 
    ggplot(aes(spreadsheet, n)) +
    geom_col(aes(fill = method), position = 'dodge') +
    labs(
        title = 'Comparison of total counts of annotations
        per spreadsheet before and after asr/inheritance',
        subtitle = 'Majority vote counts include 
        original annotations + propagated',
        x = 'Spreadsheet', y = '# annotations'
    ) +
    scale_fill_brewer(type = 'qual', palette = 'Set1') +
    theme_bw() +
    theme(
        panel.grid.major.y = element_blank()
    ) +
    coord_flip()
```

# Session info

```{r}
sessionInfo()
```
