---
title: "uncertainty_binary"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ape)
library(phytools)
library(dplyr)
library(tidyr)
```


```{r}
data('primate.tree')
data('primate.data')
tree <- primate.tree
data <- primate.data
original <- data |>
    # filter(Activity_pattern == 'Diurnal') |> 
    tibble::rownames_to_column(var = 'Taxa') |>
    select(Taxa, Activity_pattern) |>
    mutate(Presence = 1) |>
    pivot_wider(
        names_from = 'Activity_pattern', values_from = 'Presence',

                values_fill = 0
    ) |>
    arrange(Taxa) |>
    tibble::column_to_rownames(var = 'Taxa') |>
    select(Diurnal) |> 
    mutate(
        not_diurnal = ifelse(Diurnal == 0, 1, 0)
    ) |> 
    as.matrix()
colnames(original) <- c('A--TRUE', 'A--FALSE')

myFun <- function(mat, per_uncertain = 0.1) {
    n_row <- nrow(mat)
    n <- round(n_row * per_uncertain)
    rows <- sample(x = 1:nrow(mat), size = n, replace = FALSE)
    mat[rows,] <- rep(1/ncol(mat), ncol(mat))
    mat
}

```


## 99% uncertainty

```{r}
set.seed(123)
m99 <- myFun(original, 0.99)
m99 <- m99[tree$tip.label,]
fit99 <- fitMk(tree = primate.tree, x = m99,
              model = "ARD", pi = "fitzjohn",
              lik.func = "pruning", logscale = TRUE)
ace99 <- ancr(fit99, tips=TRUE)
plot(ace99, args.plotTree = list(direction="upwards"))
title(main = '99% uncertain tips', line = -1)
```

## 95% uncertainty

```{r}
set.seed(123)
m95 <- myFun(original, 0.95)
m95 <- m95[tree$tip.label,]
fit95 <- fitMk(tree = primate.tree, x = m95,
              model = "ARD", pi = "fitzjohn",
              lik.func = "pruning", logscale = TRUE)
ace95 <- ancr(fit95, tips=TRUE)
plot(ace95, args.plotTree = list(direction="upwards"))
title(main = '95% uncertain tips', line = -1)

```

## 75% uncertainty

```{r}
set.seed(123)
m75 <- myFun(original, 0.75)
m75 <- m75[tree$tip.label,]
fit75 <- fitMk(tree = primate.tree, x = m75,
              model = "ARD", pi = "fitzjohn",
              lik.func = "pruning", logscale = TRUE)
ace75 <- ancr(fit75, tips=TRUE)
plot(ace75, args.plotTree = list(direction="upwards"))
title(main = '75% uncertain tips', line = -1)
```

## No uncertainty
```{r}
fit <- fitMk(tree = primate.tree, x = original,
              model = "ARD", pi = "fitzjohn",
              lik.func = "pruning", logscale = TRUE)
ace <- ancr(fit, tips=TRUE)
plot(ace, args.plotTree = list(direction="upwards"))
title(main = '0% uncertain tips', line = -1)
```


# Imputed zeros

```{r}
myFun2 <- function(vct, per_ones = 0.1) {
    ones <- which(vct == 1)
    zeros <- which(vct == 0)
    perN <- round(per_ones * length(vct))
    
    if (perN == length(ones)) {
        new_vct <- vct
    } else if (perN < length(ones)) {
        keep_ones <- sample(ones, perN, replace = FALSE)
        new_vct <- rep(0, length(vct))
        new_vct[keep_ones] <- 1
    } else if (perN > length(ones)) {
        need_more <- perN - length(ones)
        new_ones <- sample(zeros, need_more, replace = FALSE)
        new_vct <- vct
        new_vct[new_ones] <- 1
    }
    return(new_vct)
}

```

## 95% imputed zeros

```{r}
x1 <- original
set.seed(123)
x1[,1] <- myFun2(x1[,1], 0.05)
x1[,2] <- ifelse(x1[,1] == 1, 0, 1)

x1 <- x1[tree$tip.label,]
fit_x1 <- fitMk(tree = primate.tree, x = x1,
              model = "ARD", pi = "fitzjohn",
              lik.func = "pruning", logscale = TRUE)
ace_x1 <- ancr(fit_x1, tips=TRUE)
plot(ace_x1, args.plotTree = list(direction="upwards"))
title(main = '95% imputed zeros A--FALSE', line = -1)
```

## 75% imputed zeros

```{r}
x2 <- original
set.seed(123)
x2[,1] <- myFun2(x2[,1], 0.25)
x2[,2] <- ifelse(x2[,1] == 1, 0, 1)

x2 <- x2[tree$tip.label,]
fit_x2 <- fitMk(tree = primate.tree, x = x2,
              model = "ARD", pi = "fitzjohn",
              lik.func = "pruning", logscale = TRUE)
ace_x2 <- ancr(fit_x2, tips=TRUE)
plot(ace_x2, args.plotTree = list(direction="upwards"))
title(main = '75% imputed zeros A--FALSE', line = -1)
```















