---
title: "Uncertainty in tips with multistate(-intersection) annotations"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
options(rstudio.viewer.autorefresh = FALSE)
library(ape)
library(phytools)
library(dplyr)
library(tidyr)
```

## Prepare data and tree

```{r}
## ARD with fitzjohn
## ER with fitzjohn
## ER with estimated
myMod <- 'ARD' # ARD*, ER
myPi <- 'fitzjohn' # fitzjohn*, equal, estimated
data('primate.tree')
data('primate.data')
tree <- primate.tree
data <- primate.data
data <- data[tree$tip.label,]
original <- data |>
    tibble::rownames_to_column(var = 'Taxa') |>
    select(Taxa, Activity_pattern) |>
    mutate(Presence = 1) |>
    pivot_wider(
        names_from = 'Activity_pattern', values_from = 'Presence',

                values_fill = 0
    ) |>
    arrange(Taxa) |>
    tibble::column_to_rownames(var = 'Taxa') |>
    as.matrix()
colnames(original) <- c(LETTERS[1:3])

myFun <- function(mat, per_uncertain = 0.1) {
    n_row <- nrow(mat)
    n <- round(n_row * per_uncertain)
    rows <- sample(x = 1:nrow(mat), size = n, replace = FALSE)
    mat[rows,] <- rep(1/ncol(mat), ncol(mat))
    mat
}
```


# No uncertainty

```{r}
fit <- fitMk(tree = tree, x = original,
              model = myMod, pi = myPi,
              lik.func = "pruning", logscale = TRUE)
ace <- ancr(fit, tips=TRUE)
plot(ace, args.plotTree = list(direction="upwards"))
title(main = '0% uncertain tips', line = -1)
```

## Uncertainty about 12%

```{r}
macaca <- grep('^Macaca_', rownames(original)) # A
galago <- grep('^Galago_', rownames(original)) # B
eulemur <- grep('^Eulemur', rownames(original)) # C
paste0(round((length(macaca) + length(galago) + length(eulemur)) / 90 * 100), '%')
```



```{r}
m1 <- original
m1[] <- 1 / 3
m1[macaca, ] <- c(rep(1,3), rep(0, 6))
m1[galago, ] <- c(rep(0,4), rep(1, 4), rep(0, 4))
m1[eulemur, ] <- c(rep(0,8), rep(1, 4))

fit1 <- fitMk(tree = tree, x = m1,
              model = myMod, pi = myPi,
              lik.func = "pruning", logscale = TRUE)
ace1 <- ancr(fit1, tips=TRUE)
plot(ace1, args.plotTree = list(direction = "upwards"))
title(main = '12% uncertain tips', line = -1)
```


Let's add some more taxa

```{r}
cebus <- grep('^Cebus_', rownames(original)) # A
microcebus <- grep('^Microcebus', rownames(original)) # B
paste0(round((length(macaca) + length(galago) + length(eulemur) + length(cebus) + length(microcebus)) / 90 * 100), '%')
```


```{r}
m2 <- original
m2[] <- 1 / 3
m2[macaca, ] <- c(rep(1,3), rep(0, 6))
m2[galago, ] <- c(rep(0,4), rep(1, 4), rep(0, 4))
m2[eulemur, ] <- c(rep(0,8), rep(1, 4))
m2[cebus, ] <- c(rep(1,2), rep(0, 4))
m2[microcebus, ] <- c(rep(0,2), rep(1, 2), rep(0, 2))

fit2 <- fitMk(tree = tree, x = m2,
              model = myMod, pi = myPi,
              lik.func = "pruning", logscale = TRUE)
ace2 <- ancr(fit2, tips=TRUE)
plot(ace2, args.plotTree = list(direction = "upwards"))
title(main = '17% uncertain tips', line = -1)
```

# Session information

```{r}
sessioninfo::session_info()
```

