library(taxPPro)
library(data.tree)
tbl <- getNCBI()
tree <- as.Node(tbl[, 'pathString', drop = FALSE], pathDelimiter = '|||')
tree$Do(addStrains)
tree_list <- as.list(tree)
usethis::use_data(tree_list, overwrite = TRUE)
