library(taxPPro)
library(data.tree)
tbl <- getNCBI()
tree <- as.Node(tbl[, 'pathString', drop = FALSE], pathDelimiter = '|||')
start_time <- Sys.time()
tree$Do(addStrains)
end_time <- Sys.time()
elapsed_time <- difftime(end_time, start_time)
tree_list <- as.list(tree)
usethis::use_data(tree_list, overwrite = TRUE)
